[package]
name = "renamed_num_enum"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.renamed]
package = "num_enum"
path = "../num_enum"
default-features = false

[features]
std = ["renamed/std"]
